### ISSUE TITLE
폴더, 파일이름 추가

### ISSUE THREAD

**Issue by pukuba** [windowdong11/boj-best-code-downloader#2]
문제에 따른 코드를 다운받고 코드가 폴더에 담겼으면 좋겠어요 예를들어서 1000번을 풀었으면

01000/01000.cpp14.cpp 

위와 같이 폴더랑 파일이 생겼으면 좋을거같아오

**Comment by windowdong11** [comment]
[문제번호].[솔루션번호].[사용언어].[언어에 맞는 확장자]에서
[문제번호]/[문제번호].[사용언어].[언어에 맞는 확장자] 이런형식으로 바꿀게오

**Comment by windowdong11** [comment]
방금 커밋으로 해결된것으로 보고 닫을게오

**Comment by windowdong11** [comment]
폴더가 의도와 다르게 정렬되는 문제 발생
![image](https://user-images.githubusercontent.com/16981721/105185120-83785480-5b73-11eb-95a1-2371be0b706a.png)
